name: Fast DXVK-Sarek ARM64EC build (MSVC)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build ARM64EC from Sarek main (no extras)
    runs-on: windows-2022
    timeout-minutes: 60
    env:
      SAREK_REPO: pythonlover02/DXVK-Sarek
      PREFIX_ARM64EC: ${{ github.workspace }}\dist-arm64ec

    steps:
      - name: Ensure Git & Python tooling
        run: |
          $ErrorActionPreference = 'Stop'
          python -V
          git --version
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Install Vulkan SDK (headers/tools only)
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Activate VS DevCmd (x64 host)
        run: |
          $ErrorActionPreference = 'Stop'
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vswhere)) { throw "vswhere not found" }
          $instPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          if (-not $instPath) { throw "VS installation not found" }
          $bat = Join-Path $instPath "Common7\Tools\VsDevCmd.bat"
          & cmd /c "`"$bat`" -arch=x64 -host_arch=x64 >nul && set" |
            ForEach-Object {
              if ($_ -match '^(.*?)=(.*)$') {
                [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
              }
            }

      - name: Create cl/lib wrappers + ARM64EC shim
        run: |
          $ErrorActionPreference = 'Stop'
          # 1) clwrap: normalize bad flags (-arm64EC), drop /Od, enforce /O2
          $clwrap = @'
          param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
          $out = New-Object System.Collections.Generic.List[string]
          foreach ($a in $Args) {
            if ($a -match '^-+arm64ec$') { $out.Add('/arm64EC'); continue }
            if ($a -ieq '/Od') { continue } # drop debug opt
            $out.Add($a)
          }
          if (-not ($out -contains '/arm64EC')) { $out.Add('/arm64EC') }
          if (-not ($out -contains '/O2'))      { $out.Add('/O2') }
          & cl.exe @out
          exit $LASTEXITCODE
          '@
          Set-Content -Path "$env:GITHUB_WORKSPACE\clwrap.ps1" -Value $clwrap -Encoding ascii

          # 2) libwrap: response-file to avoid arg length issues
          $libwrap = @'
          param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
          $rsp = [System.IO.Path]::GetTempFileName()
          Set-Content -Path $rsp -Encoding ascii -Value ($Args -join [Environment]::NewLine)
          & lib.exe "@$rsp"
          $code = $LASTEXITCODE
          Remove-Item $rsp -Force -ErrorAction SilentlyContinue
          exit $code
          '@
          Set-Content -Path "$env:GITHUB_WORKSPACE\libwrap.ps1" -Value $libwrap -Encoding ascii

          # 3) ARM64EC shim header: SSE guards + tzcnt/lzcnt fallback
          $shim = @'
          #pragma once
          #include <intrin.h>
          #if defined(_M_ARM64EC)
            #undef __SSE__
            #undef __SSE2__
            #undef __AVX__
            #undef __AVX2__
          #endif
          #if defined(_M_ARM64) || defined(_M_ARM64EC)
            static __forceinline unsigned int __dxvk_tzcnt_u32(unsigned int x){ unsigned long i; if (_BitScanForward(&i,x)) return (unsigned)i; return 32u; }
            static __forceinline unsigned int __dxvk_lzcnt_u32(unsigned int x){ if(!x) return 32u; unsigned long m; _BitScanReverse(&m,x); return 31u-(unsigned)m; }
            #ifndef _tzcnt_u32
            #define _tzcnt_u32 __dxvk_tzcnt_u32
            #endif
            #ifndef _lzcnt_u32
            #define _lzcnt_u32 __dxvk_lzcnt_u32
            #endif
          #endif
          '@
          Set-Content -Path "$env:GITHUB_WORKSPACE\arm64ec_shim.h" -Value $shim -Encoding ascii

      - name: Create Meson cross file (MSVC ARM64EC)
        run: |
          $work = ($env:GITHUB_WORKSPACE -replace '\\','\\')
          $shim = ("$env:GITHUB_WORKSPACE\arm64ec_shim.h" -replace '\\','\\')
          $cross = @"
          [binaries]
          c = ['pwsh','-File','@WORK@\\clwrap.ps1']
          cpp = ['pwsh','-File','@WORK@\\clwrap.ps1']
          ar = ['pwsh','-File','@WORK@\\libwrap.ps1','/MACHINE:ARM64EC']
          windres = 'rc'

          [host_machine]
          system = 'windows'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'

          [built-in options]
          cpp_std = 'c++17'
          c_args = ['/DNOMINMAX','/permissive-','/EHsc','/FI','@SHIM@','/D__SSE__=0','/D__SSE2__=0','/D__AVX__=0','/D__AVX2__=0','/wd4146']
          cpp_args = ['/DNOMINMAX','/permissive-','/EHsc','/FI','@SHIM@','/D__SSE__=0','/D__SSE2__=0','/D__AVX__=0','/D__AVX2__=0','/wd4146']
          c_link_args   = ['/MACHINE:ARM64EC']
          cpp_link_args = ['/MACHINE:ARM64EC']
          "@
          $cross = $cross -replace '@WORK@', $work
          $cross = $cross -replace '@SHIM@', $shim
          Set-Content -Path "$env:GITHUB_WORKSPACE/arm64ec.msvc" -Value $cross -Encoding ascii

      - name: Clone DXVK-Sarek (main branch, shallow)
        run: |
          git clone --depth 1 --branch main --recurse-submodules "https://github.com/$env:SAREK_REPO.git" src

      - name: Quick patching for MSVC build (disable d3d8, retag HUD)
        run: |
          Set-Location src
          # Disable d3d8 subdir (WinSDK lacks d3d8.h)
          foreach ($f in @('meson.build','src\meson.build')) {
            if (Test-Path $f) {
              $txt = Get-Content $f -Raw
              $new = $txt -replace "(?m)^\s*subdir\('d3d8'\)\s*$",""
              if ($new -ne $txt) { Set-Content -Encoding ascii $f $new }
            }
          }
          # Minimal local tag to make any version queries robust
          git config user.name  ci
          git config user.email ci@local
          git tag -a v0-ci -m ci 2>$null

      - name: Prepare LIB paths + stub d3d9.lib if missing (ARM64EC)
        run: |
          function Add-LibPathsFor([string]$Arch){
            $vc  = $env:VCToolsInstallDir
            $sdk = $env:WindowsSdkDir
            $ver = $env:WindowsSDKLibVersion
            $paths = @()
            if ($vc)  { $paths += "$vc\lib\$Arch" }
            if ($sdk -and $ver) {
              $paths += "$sdk\Lib\$ver\ucrt\$Arch"
              $paths += "$sdk\Lib\$ver\um\$Arch"
            }
            $paths = $paths | Where-Object { $_ -and (Test-Path $_) }
            if ($paths.Count -eq 0) { throw "No LIB path found for $Arch" }
            $env:LIB = ($paths -join ';') + ';' + $env:LIB
          }
          function Ensure-StubD3D9([string]$Arch){
            $need = $true
            foreach ($p in ($env:LIB -split ';')) { if ($p -and (Test-Path (Join-Path $p 'd3d9.lib'))) { $need = $false; break } }
            if ($need) {
              $stubDir = Join-Path $env:GITHUB_WORKSPACE "stublibs\$Arch"
              New-Item -ItemType Directory -Force -Path $stubDir | Out-Null
              & lib.exe /nologo /machine:$Arch /OUT:(Join-Path $stubDir 'd3d9.lib')
              if ($LASTEXITCODE -ne 0) { throw "Failed to create stub d3d9.lib ($Arch)" }
              $env:LIB = "$stubDir;" + $env:LIB
              Write-Host "Injected stub d3d9.lib -> $stubDir"
            }
          }
          Add-LibPathsFor 'arm64ec'
          Ensure-StubD3D9 'ARM64EC'

      - name: Configure (Meson) — ARM64EC
        run: |
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\build.ec" | Out-Null
          Set-Location "$env:GITHUB_WORKSPACE\src"
          meson setup "$env:GITHUB_WORKSPACE\build.ec" `
            --cross-file "$env:GITHUB_WORKSPACE\arm64ec.msvc" `
            --buildtype release `
            --prefix "$env:PREFIX_ARM64EC" `
            -Ddefault_library=shared `
            -Dbuild_id=false

      - name: Build (ninja) — ARM64EC
        run: |
          ninja -C "$env:GITHUB_WORKSPACE\build.ec" -j 2

      - name: Install — ARM64EC
        run: |
          meson install --no-rebuild -C "$env:GITHUB_WORKSPACE\build.ec"
          if (-not (Test-Path "$env:PREFIX_ARM64EC\bin")) { throw "No ARM64EC binaries produced" }

      - name: Upload binaries (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-sarek-arm64ec-bin
          path: |
            ${{ env.PREFIX_ARM64EC }}\bin\*.dll
            ${{ github.workspace }}\build.ec\meson-logs\**

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: meson-logs
          path: ${{ github.workspace }}\build.ec\meson-logs\**
