name: Build DXVK-Sarek (arm64ec + i686)

on:
  workflow_dispatch: {}

permissions:
  contents: read

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  build:
    name: Fast DLL build (arm64ec + i686)
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    env:
      SAREK_REPO: pythonlover02/DXVK-Sarek
      PREFIX_ARM64EC: ${{ github.workspace }}/dist-arm64ec
      PREFIX_I686: ${{ github.workspace }}/dist-i686
      TOOLCHAIN_ARM64EC: ${{ github.workspace }}/.toolchains/llvm-mingw-arm64ec
      TOOLCHAIN_LLVM_MINGW: ${{ github.workspace }}/.toolchains/llvm-mingw
    steps:
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            curl xz-utils jq ca-certificates git meson ninja-build \
            glslang-tools pkg-config build-essential python3 zstd file rsync

      - name: Ensure glslang (--vn) available
        run: |
          cat > /tmp/min.comp <<'GLSL'
          #version 450
          void main() {}
          GLSL
          have() { command -v "$1" >/dev/null 2>&1 || return 1; "$1" --quiet --target-env vulkan1.3 --vn testvar -o /tmp/min.h /tmp/min.comp; }
          if have glslang; then :
          elif have glslangValidator; then
            BIN="$HOME/.local/bin"; mkdir -p "$BIN"
            ln -sf "$(command -v glslangValidator)" "$BIN/glslang"
            echo "$BIN" >> "$GITHUB_PATH"
          else
            echo "::error::No glslang/glslangValidator with working --vn"; exit 1
          fi

      - name: Download bylaws/llvm-mingw (ARM64EC toolchain; Linux tar.gz)
        run: |
          set -Eeuo pipefail
          json="$(curl -fsSL -H "Accept: application/vnd.github+json" https://api.github.com/repos/bylaws/llvm-mingw/releases/latest)"
          # try to pick a linux tarball that contains 'arm64ec'
          url="$(echo "$json" | jq -r '.assets[] | select(.name|test("linux.*arm64ec.*\\.tar\\.gz$")) .browser_download_url' | head -n1)"
          if [ -z "$url" ]; then
            # fallback: any tar.gz mentioning arm64ec
            url="$(echo "$json" | jq -r '.assets[] | select(.name|test("arm64ec.*\\.tar\\.gz$")) .browser_download_url' | head -n1)"
          fi
          [ -n "$url" ] || { echo "::error::ARM64EC toolchain asset not found"; exit 1; }
          mkdir -p "$TOOLCHAIN_ARM64EC"
          curl -fL "$url" -o /tmp/llvm-mingw-arm64ec.tar.gz
          tar -C "$TOOLCHAIN_ARM64EC" --strip-components=1 -xzf /tmp/llvm-mingw-arm64ec.tar.gz
          echo "$TOOLCHAIN_ARM64EC/bin" >> "$GITHUB_PATH"

      - name: Download & extract llvm-mingw (i686; Ubuntu x86_64 asset)
        run: |
          set -Eeuo pipefail
          json="$(curl -fsSL -H "Accept: application/vnd.github+json" https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest)"
          url="$(echo "$json" | jq -r '.assets[] | select(.name|test("ucrt-ubuntu-.*-x86_64\\.tar\\.xz$")) .browser_download_url' | head -n1)"
          [ -n "$url" ] || { echo "::error::llvm-mingw (i686) asset not found"; exit 1; }
          mkdir -p "$TOOLCHAIN_LLVM_MINGW"
          curl -fL "$url" -o /tmp/llvm-mingw.tar.xz
          tar -C "$TOOLCHAIN_LLVM_MINGW" --strip-components=1 -xJf /tmp/llvm-mingw.tar.xz
          echo "$TOOLCHAIN_LLVM_MINGW/bin" >> "$GITHUB_PATH"

      - name: Verify toolchains in PATH
        run: |
          which arm64ec-w64-mingw32-gcc; arm64ec-w64-mingw32-gcc --version
          which i686-w64-mingw32-gcc;  i686-w64-mingw32-gcc --version
          which llvm-strip || true

      - name: Clone DXVK-Sarek (latest main + submodules)
        run: |
          git clone --recurse-submodules https://github.com/${SAREK_REPO}.git src
          cd src
          git fetch --force
          git checkout -f origin/main

      - name: Create Meson cross file (ARM64EC)
        working-directory: src
        run: |
          cat > cross-arm64ec.txt <<'EOF'
          [binaries]
          ar = 'arm64ec-w64-mingw32-ar'
          c = 'arm64ec-w64-mingw32-gcc'
          cpp = 'arm64ec-w64-mingw32-g++'
          ld = 'arm64ec-w64-mingw32-ld'
          windres = 'arm64ec-w64-mingw32-windres'
          strip = 'llvm-strip'
          widl = 'arm64ec-w64-mingw32-widl'
          # pkgconfig intentionally omitted for a lightweight build
          [host_machine]
          system = 'windows'
          cpu_family = 'aarch64'
          cpu = 'aarch64'
          endian = 'little'
          EOF

      - name: Build ARM64EC DLLs
        working-directory: src
        run: |
          meson setup "${GITHUB_WORKSPACE}/build.arm64ec" \
            --cross-file cross-arm64ec.txt \
            --buildtype release --prefix "${PREFIX_ARM64EC}" \
            -Dbuild_id=false -Dstrip=true \
            -Dc_args='-Wno-nontrivial-memcall' \
            -Dcpp_args='-Wno-nontrivial-memcall'
          ninja -C "${GITHUB_WORKSPACE}/build.arm64ec" -j"$(nproc)"
          meson install --no-rebuild -C "${GITHUB_WORKSPACE}/build.arm64ec"

      - name: Build i686 DLLs (WOW64)
        working-directory: src
        run: |
          meson setup "${GITHUB_WORKSPACE}/build.i686" \
            --cross-file build-win32.txt \
            --buildtype release --prefix "${PREFIX_I686}" \
            -Dbuild_id=false -Dstrip=true \
            -Dc_args='-Wno-nontrivial-memcall' \
            -Dcpp_args='-Wno-nontrivial-memcall'
          ninja -C "${GITHUB_WORKSPACE}/build.i686" -j"$(nproc)"
          meson install --no-rebuild -C "${GITHUB_WORKSPACE}/build.i686"

      - name: Collect DLLs
        run: |
          set -Eeuo pipefail
          mkdir -p artifacts/arm64ec artifacts/i686
          cp -v "${PREFIX_ARM64EC}/bin/"*.dll artifacts/arm64ec/ || true
          cp -v "${PREFIX_I686}/bin/"*.dll  artifacts/i686/     || true
          (ls -1 artifacts/arm64ec || true) && (ls -1 artifacts/i686 || true)

      - name: Upload artifacts (DLLs only)
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-sarek-dlls-${{ github.sha }}
          path: |
            artifacts/arm64ec/*.dll
            artifacts/i686/*.dll
          if-no-files-found: error
