name: Build FEX Stable

on:
  workflow_dispatch:              # Manual trigger (any branch)
  schedule:
    - cron: "0 18 * * *"         # Daily (UTC)

permissions:
  contents: write

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  resolve-latest:
    name: Resolve latest stable tag (API-only, fast)
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      clean_tag: ${{ steps.tag.outputs.clean_tag }}
    steps:
      - name: Resolve latest upstream stable tag (robust)
        id: tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          API="https://api.github.com"
          OWNER="FEX-Emu"
          REPO="FEX"

          auth=(-H "Authorization: Bearer ${GH_TOKEN}")
          ver=(-H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28")
          ua=(-H "User-Agent: ${GITHUB_REPOSITORY:-fexcore-stable-workflow}")

          fetch() { curl -fsSL --retry 6 --retry-delay 2 --retry-all-errors "${auth[@]}" "${ver[@]}" "${ua[@]}" "$1"; }

          # 1) Prefer official "latest" stable release
          tag="$(fetch "$API/repos/$OWNER/$REPO/releases/latest" | jq -r .tag_name)"
          # 2) Fallback to newest non-prerelease
          if [[ -z "$tag" || "$tag" == "null" ]]; then
            tag="$(fetch "$API/repos/$OWNER/$REPO/releases?per_page=20" \
                   | jq -r '[ .[] | select(.prerelease==false) ][0].tag_name // empty')"
          fi
          [[ -z "$tag" ]] && { echo "::notice::No stable release found"; exit 0; }

          # Clean version (drop leading 'FEX-' or similar)
          clean_tag="$(sed -E 's/^[Ff][Ee][Xx]-//' <<< "$tag")"

          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "clean_tag=$clean_tag" >> "$GITHUB_OUTPUT"
          echo "Latest stable: tag=$tag clean=$clean_tag"

  ensure-release:
    name: Ensure FEX-STABLE release (header only)
    needs: resolve-latest
    if: needs.resolve-latest.outputs.tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update Release (tag = FEX-STABLE)
        uses: softprops/action-gh-release@v2
        with:
          name: "FEX-STABLE"
          tag_name: "FEX-STABLE"
          prerelease: false
          make_latest: true
          body: |
            🤖 Automated FEX Stable builds (2508.1+)

            Current: ${{ needs.resolve-latest.outputs.clean_tag }}

  build-and-append:
    name: Build & append ${{ needs.resolve-latest.outputs.tag }}
    needs: [resolve-latest, ensure-release]
    if: needs.resolve-latest.outputs.tag != ''
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60

    steps:
      - name: Check if asset already exists (early exit)
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          FILENAME: fex-${{ needs.resolve-latest.outputs.clean_tag }}.wcp
        run: |
          API="https://api.github.com"
          auth=(-H "Authorization: Bearer ${GH_TOKEN}")
          ver=(-H "Accept: application/vnd.github+json")

          HTTP="$(curl -s -o /tmp/rel.json -w '%{http_code}' "${auth[@]}" "${ver[@]}" \
            "$API/repos/${REPO}/releases/tags/FEX-STABLE" || true)"

          if [[ "$HTTP" == "200" ]] && jq -e --arg N "$FILENAME" 'any(.assets[]?; .name==$N)' /tmp/rel.json >/dev/null; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "::notice::Found asset $FILENAME in FEX-STABLE; skipping job."
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Nix
        if: steps.check.outputs.skip != 'true'
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install build tools
        if: steps.check.outputs.skip != 'true'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            jq zstd curl wget git cmake ninja-build build-essential binutils xz-utils

      - name: Install llvm-mingw toolchain (Linux aarch64 host) and set PATH
        if: steps.check.outputs.skip != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -Eeuo pipefail
          API="https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest"
          auth=(-H "Authorization: Bearer ${GH_TOKEN}")
          ver=(-H "Accept: application/vnd.github+json")
      
          echo "Fetching latest llvm-mingw release for Linux aarch64 host..."
          url="$(
            curl -fsSL --retry 6 --retry-delay 2 --retry-all-errors "${auth[@]}" "${ver[@]}" "$API" \
            | jq -r '
                (
                  # 1st try: aarch64 + (ubuntu|linux) + tar.{xz,gz}
                  [ .assets[]
                    | select(.name | test("(aarch64|arm64).*(ubuntu|linux).*(tar\\.(xz|gz))$"; "i"))
                    | .browser_download_url
                  ]
                  +
                  # Fallback: aarch64 tarball, but NOT darwin/apple
                  [ .assets[]
                    | select((.name | test("aarch64.*(tar\\.(xz|gz))$"; "i"))
                             and (.name | test("(darwin|apple)"; "i") | not))
                    | .browser_download_url
                  ]
                )[0]
              '
          )"
          [[ -z "$url" || "$url" == "null" ]] && { echo "::error::llvm-mingw aarch64 tarball not found (linux/ubuntu)"; exit 1; }
      
          mkdir -p "$HOME/.toolchains/llvm-mingw"
          tmpd="$(mktemp -d)"; cd "$tmpd"
          echo "Downloading: $url"
          curl -fsSL --retry 6 --retry-delay 2 --retry-all-errors -o toolchain.tar "$url"
          tar -xf toolchain.tar -C "$HOME/.toolchains/llvm-mingw" --strip-components=1
      
          echo "$HOME/.toolchains/llvm-mingw/bin" >> "$GITHUB_PATH"
          ls "$HOME/.toolchains/llvm-mingw/bin" | grep -E '^(arm64ec|aarch64)-w64-mingw32-.*clang$' >/dev/null \
            || { echo "::error::Expected triplet compilers not found in llvm-mingw bin/"; exit 1; }

      - name: Checkout upstream FEX at tag
        if: steps.check.outputs.skip != 'true'
        uses: actions/checkout@v4
        with:
          repository: FEX-Emu/FEX
          ref: ${{ needs.resolve-latest.outputs.tag }}
          submodules: recursive
          path: src
          fetch-depth: 1

      - name: Compile FEXCore (arm64ec + wow64) with standard flags
        if: steps.check.outputs.skip != 'true'
        run: |
          set -Eeuo pipefail

          # Common flags suggested by the standard guide
          COMMON_FLAGS=(
            -DCMAKE_BUILD_TYPE=Release
            -DENABLE_LTO=False
            -DBUILD_TESTS=False
            -DENABLE_JEMALLOC_GLIBC_ALLOC=False
            -DTUNE_CPU=none
          )

          # ARM64EC (Windows ARM64EC)
          mkdir -p src/build/arm64ec && cd src/build/arm64ec
          ../../Data/nix/cmake_configure_woa64.sh ../../ -G Ninja \
            "${COMMON_FLAGS[@]}" \
            -DMINGW_TRIPLE=arm64ec-w64-mingw32 \
            -DCMAKE_INSTALL_PREFIX="$PWD/dist" \
            -DCMAKE_INSTALL_LIBDIR=lib/wine/aarch64-windows
          ninja -v
          ninja install
          cd ../../..

          # WOW64 (Windows x86-on-ARM; FEX translator side, ARM64 host DLL)
          mkdir -p src/build/wow64 && cd src/build/wow64
          ../../Data/nix/cmake_configure_woa32.sh ../../ -G Ninja \
            "${COMMON_FLAGS[@]}" \
            -DMINGW_TRIPLE=aarch64-w64-mingw32 \
            -DCMAKE_INSTALL_PREFIX="$PWD/dist" \
            -DCMAKE_INSTALL_LIBDIR=lib/wine/aarch64-windows
          ninja -v
          ninja install
          cd ../../..

      - name: Package FEXCore DLLs and WCP (both in system32 by design)
        if: steps.check.outputs.skip != 'true'
        env:
          CLEAN_TAG: ${{ needs.resolve-latest.outputs.clean_tag }}
        run: |
          set -Eeuo pipefail
          mkdir -p FEXCore_DLLs FEXCore_WCP/system32

          # Copy raw DLLs for convenience
          cp -v ./src/build/arm64ec/Bin/libarm64ecfex.dll ./FEXCore_DLLs/ || true
          cp -v ./src/build/wow64/Bin/libwow64fex.dll   ./FEXCore_DLLs/ || true

          # Place BOTH ARM64EC and WOW64 into system32 (intentional for this app)
          cp -v ./src/build/arm64ec/Bin/libarm64ecfex.dll ./FEXCore_WCP/system32/ || true
          cp -v ./src/build/wow64/Bin/libwow64fex.dll   ./FEXCore_WCP/system32/ || true

          # Optional strip (prefer llvm-strip; otherwise skip)
          if command -v llvm-strip >/dev/null 2>&1; then
            for f in ./FEXCore_WCP/system32/*.dll; do
              [ -f "$f" ] && llvm-strip "$f" || true
            done
          fi

          # Sanity check: ensure at least one DLL exists
          if ! compgen -G "FEXCore_WCP/system32/*.dll" >/dev/null; then
            echo "::error::No DLLs produced (check toolchain/Nix scripts)"; exit 1
          fi

          # Build profile.json from discovered DLLs (system32 only, by design)
          jq -n \
            --arg VER "${CLEAN_TAG}" \
            --arg DESC "FEXCore build by Ari" \
            --argjson VC 0 \
            --slurpfile S32 <(find FEXCore_WCP/system32 -maxdepth 1 -type f -name '*.dll' -printf '%f\n' \
                              | jq -Rn '[inputs | {source: ("system32/"+.), target: ("${system32}/"+.)}]') \
            '{
              type: "FEXCore",
              versionName: $VER,
              versionCode: $VC,
              description: $DESC,
              files: ($S32[0] // [])
            }' > FEXCore_WCP/profile.json

          # Create .wcp and move next to raw DLLs
          tar --zstd -C FEXCore_WCP \
            --format=gnu --owner=0 --group=0 --numeric-owner \
            -cf "fex-${CLEAN_TAG}.wcp" profile.json system32

          mv -v "fex-${CLEAN_TAG}.wcp" FEXCore_DLLs/

      - name: Append asset to release (tag = FEX-STABLE)
        if: steps.check.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "FEX-STABLE"
          files: ./FEXCore_DLLs/fex-*.wcp
