name: wowbox64 test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wowbox64:
    name: Build upstream wowbox64.dll (latest) and pack WCP
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 60
    env:
      LLVM_MINGW_VERSION: 20250430
    steps:
      - name: Install dependencies
        run: |
          set -Eeuo pipefail
          sudo apt-get update -yq
          sudo apt-get install -yq --no-install-recommends \
            git gcc-aarch64-linux-gnu cmake make python3 \
            curl ca-certificates xz-utils file binutils

      - name: Download llvm-mingw (aarch64 host)
        run: |
          set -Eeuo pipefail
          url="https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_VERSION}/llvm-mingw-${LLVM_MINGW_VERSION}-ucrt-ubuntu-22.04-aarch64.tar.xz"
          curl -fsSL "$url" -o llvm-mingw.tar.xz
          tar -xf llvm-mingw.tar.xz
          echo "$PWD/llvm-mingw-${LLVM_MINGW_VERSION}-ucrt-ubuntu-22.04-aarch64/bin" >> $GITHUB_PATH
          echo "MINGW_COMPILER_PATH=$PWD/llvm-mingw-${LLVM_MINGW_VERSION}-ucrt-ubuntu-22.04-aarch64/bin" >> $GITHUB_ENV
          echo "BOX64_PLATFORM_MACRO=-DWOW64=1 -DARM_DYNAREC=1" >> $GITHUB_ENV

      - name: Expose MinGW (aarch64) tools globally
        run: |
          set -Eeuo pipefail
          BIN="$MINGW_COMPILER_PATH"
          for t in aarch64-w64-mingw32-clang aarch64-w64-mingw32-clang++ aarch64-w64-mingw32-gcc aarch64-w64-mingw32-g++ \
                   aarch64-w64-mingw32-as aarch64-w64-mingw32-ar aarch64-w64-mingw32-ranlib \
                   aarch64-w64-mingw32-ld aarch64-w64-mingw32-windres aarch64-w64-mingw32-dlltool llvm-rc; do
            src="$BIN/$t"
            if [ -x "$src" ]; then
              sudo ln -sf "$src" "/usr/bin/$t"
            fi
          done

      - name: Sanity check llvm-mingw toolchain
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          : "${MINGW_COMPILER_PATH:?MINGW_COMPILER_PATH not set}"
          test -d "$MINGW_COMPILER_PATH" || { echo "::error::MINGW_COMPILER_PATH not a directory"; exit 1; }
          ls -la "$MINGW_COMPILER_PATH" | sed -n '1,50p'
          echo "PATH=$PATH"
          for t in aarch64-w64-mingw32-clang aarch64-w64-mingw32-clang++ aarch64-w64-mingw32-gcc aarch64-w64-mingw32-g++ \
                   aarch64-w64-mingw32-as aarch64-w64-mingw32-ar aarch64-w64-mingw32-ranlib \
                   aarch64-w64-mingw32-ld aarch64-w64-mingw32-windres aarch64-w64-mingw32-dlltool llvm-rc; do
            if ! command -v "$t" >/dev/null 2>&1; then
              echo "::error::$t not found in PATH"; missing=1
            fi
          done
          if [ "${missing:-0}" = "1" ]; then exit 1; fi

      - name: Checkout upstream Box64 (HEAD)
        uses: actions/checkout@v4
        with:
          repository: ptitSeb/box64
          fetch-depth: 1
          submodules: recursive

      - name: Record commit info
        id: git
        run: |
          set -Eeuo pipefail
          SHA=$(git rev-parse HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "short=${SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Configure and build (WOW64 external project)
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x

          : "${MINGW_COMPILER_PATH:?MINGW_COMPILER_PATH not set}"
          export PATH="$MINGW_COMPILER_PATH:$PATH"

          # 각 커맨드 탐색은 실패해도 쉘 종료 금지
          CC_CLANG="$(command -v aarch64-w64-mingw32-clang || true)"
          CXX_CLANG="$(command -v aarch64-w64-mingw32-clang++ || true)"
          CC_GCC="$(command -v aarch64-w64-mingw32-gcc || true)"
          CXX_GCC="$(command -v aarch64-w64-mingw32-g++ || true)"
          AS_BIN="$(command -v aarch64-w64-mingw32-as || true)"
          RC_BIN="$(command -v llvm-rc || command -v aarch64-w64-mingw32-windres || true)"

          # 최종 선택 및 존재 검사
          CC="${CC_CLANG:-$CC_GCC}"; CXX="${CXX_CLANG:-$CXX_GCC}"
          [ -n "${CC:-}" ]   || { echo "::error::No aarch64-w64-mingw32 C compiler found"; exit 1; }
          [ -n "${CXX:-}" ]  || { echo "::error::No aarch64-w64-mingw32 C++ compiler found"; exit 1; }
          [ -n "${AS_BIN:-}" ] || { echo "::error::aarch64-w64-mingw32-as not found"; exit 1; }
          [ -n "${RC_BIN:-}" ] || { echo "::error::llvm-rc or windres not found"; exit 1; }

          mkdir -p build
          cd build

          # CMake가 try-run에서 실행 파일 요구하지 않도록
          export CMAKE_TRY_COMPILE_TARGET_TYPE="STATIC_LIBRARY"
          # 교차 타겟 명시
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}" \
            -DCMAKE_ASM_COMPILER="${AS_BIN}" \
            -DCMAKE_RC_COMPILER="${RC_BIN}" \
            ${BOX64_PLATFORM_MACRO} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

          which aarch64-w64-mingw32-clang || true
          which aarch64-w64-mingw32-gcc || true
          which aarch64-w64-mingw32-as || true

          make -j"$(nproc)"

      - name: Locate and verify wowbox64.dll
        id: out
        run: |
          set -Eeuo pipefail
          DLL=$(find build -type f -iname 'wowbox64.dll' | head -n1 || true)
          if [ -z "$DLL" ]; then
            echo "::error::wowbox64.dll not produced"; exit 1
          fi
          file "$DLL"
          objdump -p "$DLL" | grep -qi 'machine.*ARM64' || { echo "::error::Expected ARM64 PE"; exit 1; }
          echo "dll=$DLL" >> $GITHUB_OUTPUT

      - name: Decide date code (YYMMDD, KST)
        id: date
        run: echo "code=$(TZ=Asia/Seoul date +%y%m%d)" >> $GITHUB_OUTPUT

      - name: Package WCP (WowBox64)
        id: wcp
        env:
          DATECODE: ${{ steps.date.outputs.code }}
          SHORT:    ${{ steps.git.outputs.short }}
        run: |
          set -Eeuo pipefail
          mkdir -p out
          cp "${{ steps.out.outputs.dll }}" wowbox64.dll
          cat <<'JSON' > profile.json
          {
            "type": "WOWBox64",
            "versionName": "nightly-${SHORT}",
            "versionCode": ${DATECODE},
            "description": "${DATECODE} WowBox64 Build by Ari",
            "files": [
              { "source": "wowbox64.dll", "target": "${syswow64}/wowbox64.dll" }
            ]
          }
          JSON
          tar --zstd --format=gnu --owner=0 --group=0 --numeric-owner --sort=name \
            -cf "out/wowbox64-nightly-${DATECODE}.wcp" profile.json wowbox64.dll
          echo "wcp=out/wowbox64-nightly-${DATECODE}.wcp" >> $GITHUB_OUTPUT

      - name: Upload WCP artifact
        uses: actions/upload-artifact@v4
        with:
          name: wowbox64-nightly-${{ steps.date.outputs.code }}.wcp
          path: ${{ steps.wcp.outputs.wcp }}
          if-no-files-found: error
